import 'package:flutter/foundation.dart';
import 'package:meta_seo/meta_seo.dart';

void addSeoContent() {
  if (kIsWeb) {
    MetaSEO meta = MetaSEO();
    meta.author(author: 'Ajith Ramsaran');
    meta.description(description: "Ajith's portfolio");
    meta.keywords(keywords: "Ajith Ramsaran");
    meta.keywords(keywords: "Ajith Ramsaran portfolio");
    meta.keywords(keywords: "Flutter developer");
    meta.keywords(keywords: "Flutter web developer");
    meta.keywords(keywords: "Mobile app developer");
    meta.keywords(keywords: "Flutter portfolio");
    meta.keywords(keywords: "Ajith Ramsaran projects");
    meta.keywords(keywords: "Ajith Ramsaran books");
    meta.keywords(keywords: "Ajith Ramsaran resume");
    meta.keywords(keywords: "Flutter web projects");
    meta.keywords(keywords: "Flutter mobile apps");
    meta.keywords(keywords: "High-performance mobile apps");
    meta.keywords(keywords: "Flutter animations");
    meta.keywords(keywords: "API integrations");
    meta.keywords(keywords: "User experience design");
    meta.keywords(keywords: "Adaptive UI design");
    meta.keywords(keywords: "Performance optimization");
    meta.keywords(keywords: "Flutter web development");
    meta.keywords(keywords: "Flutter app development");
    meta.keywords(keywords: "Mobile app development");
    meta.keywords(keywords: "Flutter developer portfolio");
    meta.keywords(keywords: "Ajith Ramsaran contact");
    meta.keywords(keywords: "Ajith Ramsaran LinkedIn");
    meta.keywords(keywords: "Ajith Ramsaran GitHub");
    meta.keywords(keywords: "Ajith Ramsaran blog");
    meta.keywords(keywords: "Flutter developer blog");
    meta.keywords(keywords: "Flutter tutorials");
    meta.keywords(keywords: "Flutter projects");
    meta.keywords(keywords: "Flutter examples");
    meta.keywords(keywords: "Flutter code snippets");
    meta.keywords(keywords: "Flutter widgets");
    meta.keywords(keywords: "Flutter packages");
    meta.keywords(keywords: "Flutter plugins");
    meta.keywords(keywords: "Flutter libraries");
    meta.keywords(keywords: "Flutter tools");
    meta.keywords(keywords: "Flutter resources");
    meta.keywords(keywords: "Flutter community");
    meta.keywords(keywords: "Flutter events");
    meta.keywords(keywords: "Flutter conferences");
    meta.keywords(keywords: "Flutter meetups");
    meta.keywords(keywords: "Flutter workshops");
    meta.keywords(keywords: "Flutter courses");
    meta.keywords(keywords: "Flutter training");
    meta.keywords(keywords: "Flutter certification");
    meta.keywords(keywords: "Flutter jobs");
    meta.keywords(keywords: "Flutter career");
    meta.keywords(keywords: "Flutter freelance");
    meta.keywords(keywords: "Flutter consulting");
    meta.keywords(keywords: "Flutter services");
    meta.keywords(keywords: "Flutter solutions");
    meta.keywords(keywords: "Flutter support");
    meta.keywords(keywords: "Flutter maintenance");
    meta.keywords(keywords: "Flutter updates");
    meta.keywords(keywords: "Flutter upgrades");
    meta.keywords(keywords: "Flutter migration");
    meta.keywords(keywords: "Flutter integration");
    meta.keywords(keywords: "Flutter testing");
    meta.keywords(keywords: "Flutter debugging");
    meta.keywords(keywords: "Flutter performance");
    meta.keywords(keywords: "Flutter optimization");
    meta.keywords(keywords: "Flutter security");
    meta.keywords(keywords: "Flutter best practices");
    meta.keywords(keywords: "Flutter design patterns");
    meta.keywords(keywords: "Flutter architecture");
    meta.keywords(keywords: "Flutter state management");
    meta.keywords(keywords: "Flutter navigation");
    meta.keywords(keywords: "Flutter routing");
    meta.keywords(keywords: "Flutter animations");
    meta.keywords(keywords: "Flutter transitions");
    meta.keywords(keywords: "Flutter gestures");
    meta.keywords(keywords: "Flutter touch events");
    meta.keywords(keywords: "Flutter accessibility");
    meta.keywords(keywords: "Flutter localization");
    meta.keywords(keywords: "Flutter internationalization");
    meta.keywords(keywords: "Flutter theming");
    meta.keywords(keywords: "Flutter styling");
    meta.keywords(keywords: "Flutter UI design");
    meta.keywords(keywords: "Flutter UX design");
    meta.keywords(keywords: "Flutter prototyping");
    meta.keywords(keywords: "Flutter wireframing");
    meta.keywords(keywords: "Flutter mockups");
    meta.keywords(keywords: "Flutter design systems");
    meta.keywords(keywords: "Flutter design tools");
    meta.keywords(keywords: "Flutter design resources");
    meta.keywords(keywords: "Flutter design inspiration");
    meta.keywords(keywords: "Flutter design trends");
    meta.keywords(keywords: "Flutter design tips");
    meta.keywords(keywords: "Flutter design tutorials");
    meta.keywords(keywords: "Flutter design examples");
    meta.keywords(keywords: "Flutter design projects");
    meta.keywords(keywords: "Flutter design portfolio");
    meta.keywords(keywords: "Flutter design showcase");
    meta.keywords(keywords: "Flutter design gallery");
    meta.keywords(keywords: "Flutter design blog");
    meta.keywords(keywords: "Flutter design articles");
    meta.keywords(keywords: "Flutter design guides");
    meta.keywords(keywords: "Flutter design documentation");
    meta.keywords(keywords: "Flutter design patterns");
    meta.keywords(keywords: "Flutter design principles");
    meta.keywords(keywords: "Flutter design techniques");
    meta.keywords(keywords: "Kilofarms");
    meta.keywords(keywords: "RedBlackTree");
    meta.keywords(keywords: "Radius Agent");
    meta.keywords(keywords: "Ind by Intain");
    meta.keywords(keywords: "Android app development");
    meta.keywords(keywords: "Android mobile development");
    meta.keywords(keywords: "Android developer freelance");
    meta.keywords(keywords: "Android app developer");
    meta.keywords(keywords: "Android development services");
    meta.keywords(keywords: "Android development solutions");
    meta.keywords(keywords: "Android consulting");
    meta.keywords(keywords: "Android support");
    meta.keywords(keywords: "Android maintenance");
    meta.keywords(keywords: "Android updates");
    meta.keywords(keywords: "Android upgrades");
    meta.keywords(keywords: "Android migration");
    meta.keywords(keywords: "Android integration");
    meta.keywords(keywords: "Android testing");
    meta.keywords(keywords: "Android debugging");
    meta.keywords(keywords: "Android performance optimization");
    meta.keywords(keywords: "Android app security");

    meta.keywords(keywords: "Kotlin Android development");
    meta.keywords(keywords: "Kotlin app developer");
    meta.keywords(keywords: "Kotlin MVVM Android");
    meta.keywords(keywords: "Kotlin Clean Architecture");
    meta.keywords(keywords: "Kotlin Coroutines");
    meta.keywords(keywords: "Kotlin Flow");
    meta.keywords(keywords: "Kotlin Multiplatform Mobile");
    meta.keywords(keywords: "KMM Android iOS");
    meta.keywords(keywords: "Jetpack Compose Kotlin");
    meta.keywords(keywords: "Kotlin Android architecture");

    meta.keywords(keywords: "MVVM architecture Android");
    meta.keywords(keywords: "Clean architecture Android");
    meta.keywords(keywords: "Retrofit Android");
    meta.keywords(keywords: "Room database Android");
    meta.keywords(keywords: "Jetpack Compose");
    meta.keywords(keywords: "Android Jetpack libraries");
    meta.keywords(keywords: "Dependency injection Android");
    meta.keywords(keywords: "Hilt Android");
    meta.keywords(keywords: "Dagger Android");
    meta.keywords(keywords: "LiveData Android");
    meta.keywords(keywords: "ViewModel Android");
    meta.keywords(keywords: "Navigation Component Android");
    meta.keywords(keywords: "Firebase Android");
    meta.keywords(keywords: "Play Store deployment");
    meta.keywords(keywords: "Google Play Android app");
  }
}
